server.port=3001

spring.datasource.url=jdbc:h2:file:./data/delta;DB_CLOSE_DELAY=-1;AUTO_SERVER=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.h2.console.enabled=true

jwt.secret=delta-wanted-secret-key-2026-spring-boot-jwt-signature
jwt.expiration=604800000
